### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by zmweske**
removed build components to docker-compose and organized in the process

### CODE REVIEW

**Comment by zmweske** [comment]
hey, thoughts on the compose file changes? @LindezaGrey

**Comment by LindezaGrey** [comment]
First of all thanks for contributing! I haven`t merged yet, because of the removal of the build step. Pulling some "random" image in a security sensitive context seems a bit off for me and i would like to build the stuff from scratch (in general) if it would be another example file i can merge, no problem. So that we have the original file, and then yours without the build step. Why the removal of the volume though?
best regards!

**Comment by zmweske** [comment]
Oh, I just made the volume a local file instead of a "docker" volume, we can revert that to the volume format you had originally.

**Review by LindezaGrey — APPROVED** [review]

**Comment by zmweske** [comment]
Something I noticed is that without cloning the repo and the build context in the docker compose, docker is pulling an old version from the hak5 site even though it uses the 'latest' tag. Does a freshly built image need to be pushed to docker hub?

**Comment by LindezaGrey** [comment]
You were right - i wanted to build and push the image, but the build failed. In one PR "version" was removed, but still referenced in the dockerfile. I should have checked that more carefully. Pushed a fix and built an new image. Since dockerhub is now premium for a year or so, the automated flow doesn't work so i had to do it manually

**Pull request merged**
